AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: IRIS Oculus - Serverless Backend

Globals:
  Function:
    Runtime: python3.11
    Timeout: 900
    MemorySize: 3008
    Environment:
      Variables:
        S3_BUCKET: !Ref DataBucket
        DYNAMODB_TABLE: !Ref MetadataTable
        BATCH_JOB_QUEUE: !Ref BatchJobQueue
        BATCH_JOB_DEFINITION: !Ref BatchJobDefinition

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
    Auth:
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt CognitoUserPool.Arn
          Identity:
            Header: Authorization

Parameters:
  DomainName:
    Type: String
    Default: iris-oculus.com
    Description: Custom domain name for the API

Resources:
  # S3 Bucket for storing NIFTI/DICOM files and processed models
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'iris-oculus-data-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - 'https://iris-oculus.com'
              - 'http://localhost:5173'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Cognito User Pool for authentication
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: iris-oculus-users
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UserPoolTags:
        Application: iris-oculus

  # Cognito User Pool Client (for web app)
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: iris-oculus-web
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes

  # DynamoDB Table for metadata
  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: iris-oculus-metadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-createdAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ECR Repository for Batch Docker image
  BatchECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: iris-totalsegmentator-batch
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [{
              "rulePriority": 1,
              "description": "Keep only last 3 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 3
              },
              "action": { "type": "expire" }
            }]
          }

  # IAM Role for Batch compute environment
  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      Policies:
        - PolicyName: BatchS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*'
        - PolicyName: BatchDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: !GetAtt MetadataTable.Arn

  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BatchInstanceRole

  # IAM Role for Batch service
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  # IAM Role for Batch ECS task execution
  BatchTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # Batch Compute Environment (CPU Spot Small - c5.large for minimal quota)
  BatchCPUSpotSmallComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: iris-cpu-spot-small-v4
      Type: MANAGED
      State: ENABLED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: SPOT
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 16
        DesiredvCpus: 0
        InstanceTypes:
          - c5.large  # 2 vCPUs, 4 GB RAM - minimal quota requirement
        Subnets:
          - !Ref BatchSubnet
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        Tags:
          Name: iris-batch-instance
          Application: iris-oculus
        Ec2Configuration:
          - ImageType: ECS_AL2

  # VPC for Batch (simple setup)
  BatchVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: iris-batch-vpc

  BatchSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BatchVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: iris-batch-subnet

  BatchInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: iris-batch-igw

  BatchVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BatchVPC
      InternetGatewayId: !Ref BatchInternetGateway

  BatchRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BatchVPC
      Tags:
        - Key: Name
          Value: iris-batch-rt

  BatchRoute:
    Type: AWS::EC2::Route
    DependsOn: BatchVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref BatchRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BatchInternetGateway

  BatchSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BatchSubnet
      RouteTableId: !Ref BatchRouteTable

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Batch compute environment
      VpcId: !Ref BatchVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # Batch Job Queue
  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: iris-processing-queue
      State: ENABLED
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchCPUSpotSmallComputeEnvironment

  # Batch Job Definition
  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: iris-totalsegmentator-job
      Type: container
      PlatformCapabilities:
        - EC2
      ContainerProperties:
        Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BatchECRRepository}:latest'
        Vcpus: 2
        Memory: 4096
        ExecutionRoleArn: !GetAtt BatchTaskExecutionRole.Arn
        JobRoleArn: !GetAtt BatchInstanceRole.Arn
        Environment:
          - Name: S3_BUCKET
            Value: !Ref DataBucket
          - Name: DYNAMODB_TABLE
            Value: !Ref MetadataTable
          - Name: DEVICE
            Value: cpu
          - Name: FAST
            Value: 'true'
          - Name: REDUCTION_PERCENT
            Value: '90'

  # Lambda Layer for dependencies
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: iris-dependencies
      Description: Dependencies for IRIS backend
      ContentUri: layers/dependencies/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  # Lambda Function for file upload
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-upload
      CodeUri: lambdas/upload/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  # Lambda Function for processing orchestration
  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-process
      CodeUri: lambdas/process/
      Handler: handler.lambda_handler
      Timeout: 30
      Environment:
        Variables:
          S3_BUCKET: !Ref DataBucket
          DYNAMODB_TABLE: !Ref MetadataTable
          BATCH_JOB_QUEUE: !Ref BatchJobQueue
          BATCH_JOB_DEFINITION: !Ref BatchJobDefinition
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
        - Statement:
            - Effect: Allow
              Action:
                - batch:SubmitJob
                - batch:DescribeJobs
                - batch:TagResource
              Resource:
                - !Ref BatchJobQueue
                - !Ref BatchJobDefinition
                - !Sub 'arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job/*'
      Events:
        Process:
          Type: Api
          Properties:
            Path: /process/totalseg
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  # Lambda Function for file download
  DownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-download
      CodeUri: lambdas/download/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataTable
      Events:
        GetFile:
          Type: Api
          Properties:
            Path: /files/{jobId}/{filename}
            Method: GET

  # Lambda Function to get user's images (protected with Cognito)
  MyImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-my-images
      CodeUri: lambdas/my-images/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        GetMyImages:
          Type: Api
          Properties:
            Path: /my-images
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  # Lambda Function to soft delete a study (protected with Cognito)
  DeleteStudyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-delete-study
      CodeUri: lambdas/delete-study/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
      Events:
        DeleteStudy:
          Type: Api
          Properties:
            Path: /studies/{jobId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer
        DeleteStudyOptions:
          Type: Api
          Properties:
            Path: /studies/{jobId}
            Method: OPTIONS

  # Lambda Function to update study status after upload
  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-update-status
      CodeUri: lambdas/update-status/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
      Events:
        UpdateStatus:
          Type: Api
          Properties:
            Path: /studies/{jobId}/status
            Method: PATCH
            Auth:
              Authorizer: CognitoAuthorizer
        UpdateStatusOptions:
          Type: Api
          Properties:
            Path: /studies/{jobId}/status
            Method: OPTIONS

  # Lambda Function to get job status
  GetJobStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-get-job-status
      CodeUri: lambdas/get-job-status/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref MetadataTable
          S3_BUCKET: !Ref DataBucket
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action:
                - batch:DescribeJobs
              Resource: '*'
      Events:
        GetJobStatus:
          Type: Api
          Properties:
            Path: /jobs/{jobId}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
        GetJobStatusOptions:
          Type: Api
          Properties:
            Path: /jobs/{jobId}
            Method: OPTIONS

  # Note: UpdateJobStatusFunction removed - Batch container updates DynamoDB directly

  # Lambda Function for health check
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-health
      CodeUri: lambdas/health/
      Handler: handler.lambda_handler
      Events:
        Health:
          Type: Api
          Properties:
            Path: /healthz
            Method: GET

  # Note: SageMaker resources removed - now using AWS Batch with Spot instances for cost optimization

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: IrisApiEndpoint

  DataBucketName:
    Description: S3 Bucket for data storage
    Value: !Ref DataBucket
    Export:
      Name: IrisDataBucket

  MetadataTableName:
    Description: DynamoDB Table for metadata
    Value: !Ref MetadataTable
    Export:
      Name: IrisMetadataTable

  BatchJobQueue:
    Description: AWS Batch Job Queue
    Value: !Ref BatchJobQueue
    Export:
      Name: IrisBatchJobQueue

  BatchJobDefinition:
    Description: AWS Batch Job Definition
    Value: !Ref BatchJobDefinition
    Export:
      Name: IrisBatchJobDefinition

  ECRRepository:
    Description: ECR Repository for Batch Docker images
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BatchECRRepository}'
    Export:
      Name: IrisECRRepository

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: IrisUserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: IrisUserPoolClientId

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt CognitoUserPool.Arn
    Export:
      Name: IrisUserPoolArn
