AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: IRIS Oculus - Serverless Backend

Globals:
  Function:
    Runtime: python3.11
    Timeout: 900
    MemorySize: 3008
    Environment:
      Variables:
        S3_BUCKET: !Ref DataBucket
        DYNAMODB_TABLE: !Ref MetadataTable
        SAGEMAKER_ENDPOINT_NAME: iris-totalsegmentator-endpoint

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
    Auth:
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt CognitoUserPool.Arn
          Identity:
            Header: Authorization

Parameters:
  DomainName:
    Type: String
    Default: iris-oculus.com
    Description: Custom domain name for the API

Resources:
  # S3 Bucket for storing NIFTI/DICOM files and processed models
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'iris-oculus-data-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - 'https://iris-oculus.com'
              - 'http://localhost:5173'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Cognito User Pool for authentication
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: iris-oculus-users
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UserPoolTags:
        Application: iris-oculus

  # Cognito User Pool Client (for web app)
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: iris-oculus-web
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes

  # DynamoDB Table for metadata
  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: iris-oculus-metadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-createdAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Lambda Layer for dependencies
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: iris-dependencies
      Description: Dependencies for IRIS backend
      ContentUri: layers/dependencies/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  # Lambda Function for file upload
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-upload
      CodeUri: lambdas/upload/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  # Lambda Function for processing orchestration
  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-process
      CodeUri: lambdas/process/
      Handler: handler.lambda_handler
      Timeout: 900
      Environment:
        Variables:
          SAGEMAKER_MANAGER_FUNCTION: !Ref SageMakerManagerFunction
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
        - Statement:
            - Effect: Allow
              Action:
                - sagemaker:InvokeEndpoint
                - sagemaker:InvokeEndpointAsync
              Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/iris-totalsegmentator-endpoint'
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt SageMakerManagerFunction.Arn
      Events:
        Process:
          Type: Api
          Properties:
            Path: /process/totalseg
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  # Lambda Function for file download
  DownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-download
      CodeUri: lambdas/download/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataTable
      Events:
        GetFile:
          Type: Api
          Properties:
            Path: /files/{jobId}/{filename}
            Method: GET

  # Lambda Function to get user's images (protected with Cognito)
  MyImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-my-images
      CodeUri: lambdas/my-images/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        GetMyImages:
          Type: Api
          Properties:
            Path: /my-images
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  # Lambda Function to soft delete a study (protected with Cognito)
  DeleteStudyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-delete-study
      CodeUri: lambdas/delete-study/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
      Events:
        DeleteStudy:
          Type: Api
          Properties:
            Path: /studies/{jobId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer
        DeleteStudyOptions:
          Type: Api
          Properties:
            Path: /studies/{jobId}
            Method: OPTIONS

  # Lambda Function to update study status after upload
  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-update-status
      CodeUri: lambdas/update-status/
      Handler: handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
      Events:
        UpdateStatus:
          Type: Api
          Properties:
            Path: /studies/{jobId}/status
            Method: PATCH
            Auth:
              Authorizer: CognitoAuthorizer
        UpdateStatusOptions:
          Type: Api
          Properties:
            Path: /studies/{jobId}/status
            Method: OPTIONS

  # Lambda Function for health check
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-health
      CodeUri: lambdas/health/
      Handler: handler.lambda_handler
      Events:
        Health:
          Type: Api
          Properties:
            Path: /healthz
            Method: GET

  # SageMaker Execution Role
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: iris-sagemaker-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${DataBucket.Arn}/*'

  # SageMaker Model (to be created manually or via separate script)
  # Note: SageMaker endpoint configuration will be in a separate deployment script
  # because TotalSegmentator requires custom Docker image

  # DynamoDB Table for tracking SageMaker endpoint activity (auto-sleep)
  SageMakerActivityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: iris-sagemaker-activity
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: endpoint
          AttributeType: S
      KeySchema:
        - AttributeName: endpoint
          KeyType: HASH

  # Lambda function for SageMaker endpoint auto-wake/sleep management
  SageMakerManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/sagemaker-manager/
      Handler: handler.lambda_handler
      Timeout: 900
      Environment:
        Variables:
          ENDPOINT_NAME: iris-totalsegmentator-endpoint
          ENDPOINT_CONFIG: iris-totalsegmentator-config-autoscale
          ACTIVITY_TABLE: !Ref SageMakerActivityTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SageMakerActivityTable
        - Statement:
          - Effect: Allow
            Action:
              - sagemaker:DescribeEndpoint
              - sagemaker:CreateEndpoint
              - sagemaker:DeleteEndpoint
              - sagemaker:UpdateEndpoint
            Resource:
              - !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/iris-totalsegmentator-endpoint'
              - !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint-config/iris-totalsegmentator-config-autoscale'

  # Note: EventBridge rule for auto-sleep will be configured manually after deployment
  # due to CloudFormation permission limitations with EventBridge

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: IrisApiEndpoint

  DataBucketName:
    Description: S3 Bucket for data storage
    Value: !Ref DataBucket
    Export:
      Name: IrisDataBucket

  MetadataTableName:
    Description: DynamoDB Table for metadata
    Value: !Ref MetadataTable
    Export:
      Name: IrisMetadataTable

  SageMakerRoleArn:
    Description: SageMaker Execution Role ARN
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: IrisSageMakerRole

  SageMakerManagerFunction:
    Description: SageMaker Manager Lambda Function (for auto-wake/sleep)
    Value: !Ref SageMakerManagerFunction
    Export:
      Name: IrisSageMakerManagerFunction

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: IrisUserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: IrisUserPoolClientId

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt CognitoUserPool.Arn
    Export:
      Name: IrisUserPoolArn
